### ISSUE TITLE
User Story 1 - List of lost or found items

### ISSUE THREAD

**Issue by Olga-Mishareva** [Olga-Mishareva/capstone-project-lost-n-found#1]
## Value Proposition

**As a**  user  
**I want to** be able to have a list of lost and found things 
**so that**  I can find the owner or item 

## Description

![user-story-1_wireframe_simple](https://user-images.githubusercontent.com/94528652/213491664-c7fc81db-c8b8-4acf-b961-e041fc32b456.png)

## Acceptance Criteria

- [x] title of app is always visible in the title bar
- [x] all things from the static JSON are displayed as list at home page
- [x] every item shows the name of the thing
- [x] every item is marked with specific color: lost - red, found - blue

## Tasks

- [x] create the title bar component with app title 
- [x] create a json file with a data structure:
```
[
  {
    initiallyLost: true/false,
    itemId: "",
    itemTitle: "",
    itemDescription: "",
    userName: "",
    userId: "",
  }
]
```
- [x] create a list item component for every lost and found thing
- [x] map over list from the JSON to display the items

## Complexity

S

**Comment by mbosselmann** [comment]
Hi Olga,
great job! 👍 We have some remarks for you:

**Value proposition**
- We propose as value proposition:

As a user
I want to be able to have a list of lost and found things
so that I can find the owner or item

- We think this value proposition describes the goal of your user story better. :)

**Description & Acceptance criteria**
- We do not think that you need a user icon yet or is there a reason why there should be one in this early stage of your app? 🤔 We think: As long as there is no user a user icon is not needed.
-  You should describe more what will be displayed, for example:
- "A list of all lost and found things is displayed"
- "Every item shows the name of the thing"
- your description also indicates that every lost and found things are styled differently? Maybe this should be described in your acceptance criteria

**Tasks**
- you should create a list item component for every lost and found thing
- instead of writing data, you should describe that you need to create a json file with a data structure (the example data structure looks good to us, but the empty object should be removed)

Aaaaaand: You may think about a descriptive title for this user story in addition to the user story number.

If you have questions, feel free to ask us! After editing your user story, please post the user story again in our thread. :)

**Comment by Olga-Mishareva** [comment]
- edit value proposition
- remove user icon from first user story
- add to acceptance criteria displaying the title and color of items
- add tasks for creating item component and json file
- edit data structure (remove empty object)
- add descriptive title to user story

**Comment by Olga-Mishareva** [comment]
Hallo Robin,
thank you for your feedback!
Yoг're right, I'll add other condition later, but for initial condition is only one boolean enough.  

- edit data structure (only one boolean for initial condition)
