### ISSUE TITLE
User Story 6 - Adding map to home page

### ISSUE THREAD

**Issue by Olga-Mishareva** [Olga-Mishareva/capstone-project-lost-n-found#10]
## Value Proposition

**As a** user
**I want to** see the map on home page
**so that** I can see my location in the center of map 

## Description

![user-story-6-adding-map](https://user-images.githubusercontent.com/94528652/215423280-57adfbaa-f53f-4e72-9a0f-528e2b6daf7e.png)

## Acceptance Criteria

- [x] map is displayed on the home page for the list of items
- [x] user's location is at the centre of the map
- [x] map scaled to user's location

## Tasks

- [x] install & import leaflet library
- [x] create Map component 
- [x] create user location marker
- [x] centre and scale the map to location marker

## Complexity

M

> Can you be more diskret in the value proposition why the user wants the map to be centered in Berlin

**Comment by janneserichsen** [comment]
Can you be more diskret in the value proposition why the user wants the map to be centered in Berlin

**Comment by Olga-Mishareva** [comment]
I wanted to center to Berlin temporary. I change it to user's location now.
