### ISSUE TITLE
User Story 7 - adding Markers from DB to map

### ISSUE THREAD

**Issue by Olga-Mishareva** [Olga-Mishareva/capstone-project-lost-n-found#11]
## Value Proposition

**As a** user
**I want to** see markers on the map 
**so that** I can see different markers for lost, found and 'waiting for pick-up' items

## Description

![user-story-7-adding-markers](https://user-images.githubusercontent.com/94528652/215507837-8376eb86-7e72-4178-95fb-fa34eba414ab.png)

## Acceptance Criteria

- [ ] all markers from DB are displayed on the map
- [ ] different markers for lost and found are displayed
- [ ] items with status `inDiscuss: true` are with third type of marker displayed

## Tasks

- [ ] add Marker component from  for each item with map function 
- [ ] add icons for each status of item: lost, found and 'waiting for pick-up'
- [ ] pass on prors position (from DB) and icon for each marker

## Complexity

M

**Comment by RobinWitt** [comment]
Hi Olga, nice idea and amazing drawing of the map, hehe. One question came to my mind: At what point are items deleted from the map? Is there going to be a delete button for each item or does it depend on the status?

**Comment by Olga-Mishareva** [comment]
Hi Robin, 
thank you for checking! I have added delete function for each item now (US-6). All items will be on the map with different status / markers displayed. I want to show also finished items on the map. I'm going to add date property to my schema later to filter items with a date.

**Comment by RobinWitt** [comment]
sounds nice!
