### ISSUE TITLE
User story 8 - set new markers on the map

### ISSUE THREAD

**Issue by Olga-Mishareva** [Olga-Mishareva/capstone-project-lost-n-found#15]
## Value Proposition

**As a** user
**I want to** be able to set new markers to the map 
**so that** I can add my lost or found item to the map directly

## Description

Setting new marker to the map with click event.

## Acceptance Criteria

- [x] get latitude and longitude by setting new marker 
- [x] lat & long are used for adding new item to DB
- [x] after setting a marker it opens a form for setting other data for a new item.
- [x] new item is also displayed on the map

## Tasks

- [x] add function for getting latitude and longitude
- [x] add handler for click event
- [x] pass on lat & long by creating new item

## Complexity

S

**Comment by marcterre** [comment]
Hey Olga, in your acceptance criteria you write "after set marker open form for setting other data to new item", maybe write it out more like "after setting a marker it opens a form for setting other data for a new item." Something like that. Would be more understandable. 🙂
Nothing more to improve 🚀

**Comment by Olga-Mishareva** [comment]
Hi Marc, thank you for correction! It sounds better now :)
