### ISSUE TITLE
User Story 9 - refactoring for better user experience 

### ISSUE THREAD

**Issue by Olga-Mishareva** [Olga-Mishareva/capstone-project-lost-n-found#16]
## Value Proposition

**As a** user
**I want to**see that my request is handled by the app
**so that** I now that app works and I have only to wait 

## Description

![user-story-9-refactoring](https://user-images.githubusercontent.com/94528652/217764630-9c6f296c-b366-41ba-801f-803b3df5757a.png)

## Acceptance Criteria

- [x] the buttons is not clickable during data fetching
- [x] the buttons have lower opacity during data fetching
- [x] displaying confirm popup by delete item

## Tasks

- [x] fetch data with `useSWRMutation` by create new item
- [x] fetch data with `useSWRMutation` by edit item
- [x] fetch data with `useSWRMutation` by delete item
- [x] fetch data with `useSWRMutation` by toggle status of item
- [x] disable buttons by fetching

## Complexity

L

**Comment by JoergWolff** [comment]
Happy Hacking...LGTM
