### ISSUE TITLE
User Story 10 - adding Date and filter by date

### ISSUE THREAD

**Issue by Olga-Mishareva** [Olga-Mishareva/capstone-project-lost-n-found#17]
## Value Proposition

**As a** user
**I want to** be able filter the items
**so that** I can see only those items witch were added after specific date

## Description

![US-10_filter](https://user-images.githubusercontent.com/94528652/217003831-2a123db5-b758-4517-bdc8-0a5641082dff.png)

## Acceptance Criteria

- [ ] input for date is displayed in footer
- [ ] select input for status is displayed in footer
- [ ] items are filtered by choosing date, only filtered items are displayed
- [ ] items are filtered by choosing status, only filtered items are displayed

## Tasks

- [ ] add date property to DB schema
- [ ] create component filter
- [ ] add input for date
- [ ] add select input for status
- [ ] add filter function for date
- [ ] add filter function for status

## Complexity

M
