### ISSUE TITLE
User Story 3 - Details Page

### ISSUE THREAD

**Issue by Olga-Mishareva** [Olga-Mishareva/capstone-project-lost-n-found#2]
## Value Proposition

**As a** user 
**I want to**be able click on the item and
**so that**  I can see all info fetched from MongoDB on details page

## Description

![user-story-3](https://user-images.githubusercontent.com/94528652/214054221-4064ff87-6a44-48e1-8e80-e26bb1386ae6.png)

Schema:
```
[
  {
    initiallyLost: true/false,
    title: "",
    description: "",
    itemId: "", 
    userName: "",                 
    userId: "",                        
    userRole: "user",                    // for auth feature
    longitude: "",                          // for map feature
    latitude: "",                             // for map feature
    inDiscuss: false,
    isFinished: false,
    messages: [                   // for comments feature
                {userName: "",
                 userId: "",
                 message: ""
                }
               ]
  }
] 

```

## Acceptance Criteria

- [x] all items on home page are links to details page with info 
- [x]  thing page have:
    - [x] category title (Lost item or Found item)
    - [x]  name of owner or founder
    - [x]  title of item
    - [x]  short description of item
    - [x]  close button-link redirect back to home page
    - [x]  button for changing property in DB to `inDiscuss: true` (because this button will open the comment field later)
- [x]  in this US by click of the button text should only change from  "I found it" or "That's mine" to "Found its owner"
     

## Tasks

- [x] add folder in the pages folder containing a `[id].js`
- [x] create a details page displaying the required elements
- [x] add api endpoint in your `api/places/[id]` route for fetching specific item from database with GET request
- [x] add button for changing the property in DB on the bottom 
- [x] add event to button for changing the property in DB: `inDiscuss: true` 
- [x] change category title to "Waiting for pick-up" and button text to "Found its owner"

## Complexity

M

**Comment by SaschaRadojkovic** [comment]
Hi Olga , at all i think it is a good user story . But some little things maybe ! You have a little typo "title of think" but i think its not that relevant!  what database are you fetching from maybe you should mention this . and do you fill it with dummy data ? where in the description is the button for changing the status ?  is that the button on the bottom ?  i try to understand how this will work but can not get it yet :)  (its not easy to get into the thoughts of someone elses idea )

**Comment by Olga-Mishareva** [comment]
Hi Sascha,
thank you for checking my user story! I hope, it's easier to understand now :)

**Comment by AGeck113** [comment]
Hi Olga, looks good to me, i think you are free to go :).

**Comment by Olga-Mishareva** [comment]
> Hi Olga, looks good to me, i think you are free to go :).

Thanks! :)
