### ISSUE TITLE
User Store 11 - login with GitHub

### ISSUE THREAD

**Issue by Olga-Mishareva** [Olga-Mishareva/capstone-project-lost-n-found#20]
## Value Proposition

**As a** user
**I want to** be able to login with GitHub
**so that** I can differentiate my items from other items

## Description

![user-story-11_login](https://user-images.githubusercontent.com/94528652/217769045-a8f15212-c858-497c-ac3f-905f87765331.png)

## Acceptance Criteria

- [x] login/logout button is displayed in header right
- [x] the map with items is displayed also without login
- [x] user can login with GitHub and logout
- [x] user can't add new item without login
- [x] user can't edit or delete item without login
- [x] user can edit or delete only his own items
- [x] edit, delete, change status buttons are disabled without login
- [x] edit, delete buttons are disabled for not own items
- [x] after confirming adding new item is popup with offer to login displayed

## Tasks

- [x] add `[nextauth].js` file to backend
- [x] get GitHub keys for auth by GitHub 
- [x] add keys to .env.local and Vercel
- [x] add session provider to `_app.js`
- [x] use session for form and submit buttons
- [x] get user id from session and add them by creating new items of this user
- [x] use user  id from session to filter his own items

## Complexity

L

**Comment by niklasrammelkamp** [comment]
nice one.  👍🏻

**Comment by Olga-Mishareva** [comment]
> nice one. 👍🏻

Thank you! :)
