### ISSUE TITLE
User Story 12 - commits feature

### ISSUE THREAD

**Issue by Olga-Mishareva** [Olga-Mishareva/capstone-project-lost-n-found#21]
## Value Proposition

**As a** user 
**I want to** be able left commits 
**so that** I can inform, that I found one of lost the items or
 tell, that the found item is mine.

## Description

![US-12-commits](https://user-images.githubusercontent.com/94528652/218326879-3171b357-d283-4e13-86b6-7782c3aec44d.png)

## Acceptance Criteria

- [x] by click the button `Leave a message` is a textarea for commit displayed
- [x] submit and cancel button are displayed under textarea
- [x] user can see only commits to his own items or to items, which he left commit to
- [x] user can't left the first commit to his own items
- [x] user can see his own commit in item details after submit

## Tasks

- [x] add textarea for commit to item details page
- [x] save commits in DB with PUT request
- [x] save commits in messages array of Item schema

## Complexity

M
