### ISSUE TITLE
User Story 13 - Refactoring

### ISSUE THREAD

**Issue by Olga-Mishareva** [Olga-Mishareva/capstone-project-lost-n-found#24]
## Value Proposition

**As a** user
**I want to** be able see message button on my item, if I've got a message
**so that** I can answer 

## Description

  " - "

## Acceptance Criteria

- [x] message button is displayed on the item of current user, if there is a message from oder user 
- [x] there is information in the `readme`

## Tasks

- [x] add field `userEmail` to Item schema
- [x] compare `session.user.email` with `item.userEmail` to show correct buttons
- [x] full `readme` 

## Complexity

S
