### ISSUE TITLE
User Story 2 - Adding data base

### ISSUE THREAD

**Issue by Olga-Mishareva** [Olga-Mishareva/capstone-project-lost-n-found#3]
## Value Proposition

**As a** user
**I want to** share extended data from a database  
**so that**  I can see all lost or found items on different devices

## Description

Schema:
```
[
  {
    initiallyLost: true/false,
    title: "",
    description: "",
    itemId: "", 
    userName: "",                 
    userId: "",                        
    userRole: "user",            // for auth feature
    longitude: "",                             // for map feature
    latitude: "",                              // for map feature
    inDiscuss: false,
    isFinished: false,
    messages: [                   // for comments feature
                {userName: "",
                 userId: "",
                 message: ""
                }
               ]
  }
] 

```
## Acceptance Criteria

- [x] all items are displayed from fetched data
- [x] data in database matches with schema (see above)

## Tasks

- [x] create DB
- [x] prepare the database connection
- [x] create a DB function to find all items
- [x] create an api endpoint in api/items route for fetching all items from DB
- [x] map over the fetched items to render the cards

## Complexity

L

**Comment by RobinWitt** [comment]
Hi Olga,
keep in mind that, even though it is not easy, the Value Proposition should always be written from the perspective of a User of your app. Think about what the benefit for the User could be from the changes you want to make. (for example: "As a User, I want to share my entries and they should be available from different browsers")

The criteria and tasks are well described in my opinion, although I think the complexity level is at least L for this User Story.

Have a great weekend!

**Comment by Olga-Mishareva** [comment]
Hi Robin, 
thank you for reviewing! Assess the complexity is difficult for me for some reason 🙃

- edit value proposition
- edit complexity

**Comment by Long-HaHoang** [comment]
Hi Olga,

in my opinion I would use `longitude` and `latitude` instead of `lon` and `lat`.
It's more descriptive. 
As fellow developer I can see more clear where to store my coordinates. 

The authentication and chat is kind of a complex topic.
Authentication and Login is tied to security like I said it's complex.
The chat function is not simple either, maybe consider a comment section instead?

**Comment by Olga-Mishareva** [comment]
Hi Long, 
thank you for your feedback! I edit `longitude` and `latitude` properties. 
I have already done authentication for my other projects. And with chat feature I actually meant comments :) I fix it too.

**Comment by Long-HaHoang** [comment]
Perfect 👍 . You have to show me how to do the authentication. Have nice weekend

**Comment by Olga-Mishareva** [comment]
> Perfect 👍 . You have to show me how to do the authentication. Have nice weekend

I heard we'll have a session about Auth with Next.js. It would probably be easier :)
I wish you a great weekend too
