### ISSUE TITLE
User Story 4 - Form Component / Adding of new item

### ISSUE THREAD

**Issue by Olga-Mishareva** [Olga-Mishareva/capstone-project-lost-n-found#6]
## Value Proposition

**As a** user
**I want to** to be able to add new item 
**so that** I can expand the items collection.  

## Description

![user-story-4](https://user-images.githubusercontent.com/94528652/214092875-4c763bce-f9ce-48d3-bc85-36c42140a1f0.png)

## Acceptance Criteria

- [x] `Add item` link to create page is displayed on main page
- [x] `Cancel` link back to main page 
- [x] select input for Lost/Found item
- [x] input for user name
- [x] input for title of item
- [x] textarea for short description of item
- [x] `Submit` button adds new item to DB
- [x] after submit user will be redirected to home page
- [x] new item will be added as the first item of the list

## Tasks

- [x] create a component ItemForm with form for adding new items
- [x] create a CreatePage for displaying of ItemForm component  
- [x] add a link for adding new item on main page 
- [x] add back link on create page
- [x] submit function send a POST request to the `api/items` endpoint with the new data in the body
- [x] expand the api endpoint to handle POST requests
- [x] with the received data, create a new item in DB
- [x] adding new item to list on HomePage
- [x] reroute the user to HomePage after successful POST request

## Complexity

M

**Comment by AGeck113** [comment]
Looks very well structured!
