### ISSUE TITLE
User Story 5 - Edit and delete item

### ISSUE THREAD

**Issue by Olga-Mishareva** [Olga-Mishareva/capstone-project-lost-n-found#8]
## Value Proposition

**As a** user
**I want to** to be able to edit my items and delete (there is no auth-function now, each user can edit and delete any item now) 
**so that** I can edit title, description or category of item or delete it. I can't edit name of user from edit item page.

## Description

![user-story-5-edit- -delete](https://user-images.githubusercontent.com/94528652/214809810-1298f6fc-792e-4cc0-8f69-d8d28da0ab80.png)

## Acceptance Criteria

- [x] `Link` to edit page is added to details page
- [x] `delete` button is added to details page
- [x] on edit page is displayed: 
    - [x] select input for Lost or Found item with previous option
    - [x] input for title of item with previous title
    - [x] textarea for short description with previous text
    - [x] `submit` button changed item data in the DB
    - [x] `cancel` link back to details page
- [x] name of user can't changed from edit item page

## Tasks

- [x]  add `Link` to edit page to details page
- [x] add `delete` button to details page
- [x] create EditPage component
- [x] create edit page
- [x] fetch data with method "PATCH"
- [x] fetch data with method "DELETE"
- [x] add PATCH & DELETE requests and functions

## Complexity

M

**Comment by minatimar** [comment]
hi olga, on the drawing of the editpage you have a typo. its thinG not thinK.

**Comment by Olga-Mishareva** [comment]
Hi Mina, thank you for checking! I fixed it :)

**Comment by minatimar** [comment]
great :) happy hacking :)
